/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface DonationSubmission {
  'id' : bigint,
  'cause' : string,
  'name' : string,
  'recurring' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export interface NewsletterSignup {
  'id' : bigint,
  'email' : string,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export interface VolunteerSignup {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'email' : string,
  'motivation' : string,
  'timestamp' : Timestamp,
}
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getDonationSubmissions' : ActorMethod<[], Array<DonationSubmission>>,
  'getNewsletterSignups' : ActorMethod<[], Array<NewsletterSignup>>,
  'getVolunteerSignups' : ActorMethod<[], Array<VolunteerSignup>>,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
  'submitDonationForm' : ActorMethod<
    [string, string, string, bigint, boolean, string],
    bigint
  >,
  'submitNewsletterSignup' : ActorMethod<[string], bigint>,
  'submitVolunteerSignup' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];