/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const DonationSubmission = IDL.Record({
  'id' : IDL.Nat,
  'cause' : IDL.Text,
  'name' : IDL.Text,
  'recurring' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const NewsletterSignup = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Text,
  'timestamp' : Timestamp,
});
export const VolunteerSignup = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'motivation' : IDL.Text,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getDonationSubmissions' : IDL.Func(
      [],
      [IDL.Vec(DonationSubmission)],
      ['query'],
    ),
  'getNewsletterSignups' : IDL.Func([], [IDL.Vec(NewsletterSignup)], ['query']),
  'getVolunteerSignups' : IDL.Func([], [IDL.Vec(VolunteerSignup)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitDonationForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitNewsletterSignup' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitVolunteerSignup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const DonationSubmission = IDL.Record({
    'id' : IDL.Nat,
    'cause' : IDL.Text,
    'name' : IDL.Text,
    'recurring' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const NewsletterSignup = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const VolunteerSignup = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'motivation' : IDL.Text,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getDonationSubmissions' : IDL.Func(
        [],
        [IDL.Vec(DonationSubmission)],
        ['query'],
      ),
    'getNewsletterSignups' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSignup)],
        ['query'],
      ),
    'getVolunteerSignups' : IDL.Func([], [IDL.Vec(VolunteerSignup)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitDonationForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitNewsletterSignup' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitVolunteerSignup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };